# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3676ae64277b810e48ec1d9d54b8617378f86866cb3ad452cfe444f99c63f3674c072a25a4165a0388aecd17c7f84789319f2ff15b387f9387d7621b4ff25fe

test:
  secret_key_base: d00e07735ced10404cdb503de1e10b314db1f28908cb0ac23a3a4d710940fc433eab2476d9c066f42419e72cd5dd4759276b4041c55fd6d511c62608b3a6306a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
